const THEME_COLOR = '#00386D';
const THEME_ORANGE = '#FB724C';
const THEME_RED = '#FB5454';
const WHITE = '#FFFFFF';
const BLACK = '#000000';
const RED = '#FF0000';
const BACKGROUND_COLOR = '#EFEDF4';
const LIGHT_GRAY = '#F1F4FF';
const GRAY = '#A1A1A1';
const DARK_GRAY = '#494949';
const BOTTOM_GRAY = '#CBD5E1';
const CATEGORY_BG = '#E1F5FA';
const INPUT_BORDERWIDTH_GREY = '#E8E7EA';
const FORGOR_PASS = '#FB724C';
const OR_grey = '#96979F';

export {
  THEME_COLOR,
  THEME_ORANGE,
  THEME_RED,
  WHITE,
  BLACK,
  RED,
  BACKGROUND_COLOR,
  LIGHT_GRAY,
  GRAY,
  DARK_GRAY,
  BOTTOM_GRAY,
  CATEGORY_BG,
  INPUT_BORDERWIDTH_GREY,
  FORGOR_PASS,
  OR_grey,
};
